---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Create VPC Interface 
      ec2_vpc_net:
        name: ansible-vpc-test-1	
        cidr_block: 10.0.0.0/16
        region: ap-northeast-2
        tags:
          module: ec2_vpc_net
          this: works
        tenancy: dedicated
      register: ansible_vpc
      
    - name: Create Subnet1
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{ansible_vpc.vpc.id}}"
        cidr: 10.0.1.0/24
        az: ap-northeast-2a
        tags:
          Name: ansible_Subnet1
          
    - name: Create Subnet2
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{ansible_vpc.vpc.id}}"
        cidr: 10.0.2.0/24
        az: ap-northeast-2c
        tags:
          Name: ansible_Subnet2
    
    - name: Create Internet gateway
      ec2_vpc_igw:
        vpc_id: "{{ansible_vpc.id}}"
        state: present
      register: ansible_igw  
      
      
