---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Create VPC Interface 
      ec2_vpc_net:
        name: ansible-vpc-test-1	
        cidr_block: "{{vpc_cidr}}"
        region: "{{region}}"
        tags:
          module: ec2_vpc_net
          this: works
        tenancy: dedicated
      register: vpc_1
      
    - name: Create Public-Subnet-1
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpc_1.vpc.id}}"
        cidr: "{{subnet1_cidr}}"
        region: "{{region}}"
        az: "{{az_1}}"
        tags:
          Name: public_subnet_1
          
    - name: Create Private-Subnet-2
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpc_1.vpc.id}}"
        cidr: "{{subnet2_cidr}}"
        region: "{{region}}"
        az: "{{az_2}}"
        tags:
          Name: private_subnet_2
    
    - name: Create Internet gateway
      ec2_vpc_igw:
        vpc_id: "{{vpc_1.vpc.id}}"
        region: "{{region}}"
        state: present
      register: ansible_igw  
      
    - name: Create Nat Gateway 
      ec2_vpc_nat_gateway:
        state: present
        region: "{{region}}"
        subnet_id: "{{public_subnet_1.subnet.id}}"
        
      
      
