---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Create VPC Interface 
      ec2_vpc_net:
        name: "{{prefix}}"-vpc	
        cidr_block: "{{vpc_cidr}}"
        region: "{{region}}"
        tenancy: default
      register: vpc_1
