---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Create VPC Interface 
      ec2_vpc_net:
        name: "{{prefix}}-vpc"
        cidr_block: "{{vpc_cidr}}"
        region: "{{region}}"
        tenancy: default
      register: vpc_1
      
    - name: "Create Public-Subnet-{{az_1}}"
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpc_1.vpc.id}}"
        cidr: "{{public_subnet_a_cidr}}"
        region: "{{region}}"
        az: "{{region}{az_1}}"
        tags:
          Name: "{{prefix}}-pulic-subnet-{{az_1}}"
      register: "public_subnet_1"
      
    - name: "Create Public-Subnet-{{az_2}}"
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpc_1.vpc.id}}"
        cidr: "{{public_subnet_c_cidr}}"
        region: "{{region}}"
        az: "{{region}{az_2}}"
        tags:
          Name: "{{prefix}}-pulic-subnet-{{az__2}}"
      register: "public_subnet_2"
            
    - name: Create EC2 instance-2 
      ec2:
        key_name: "{{key_pair}}"
        image: ami-08f90fed89a37985d
        instance_type: m5.xlarge
        region: "{{ region }}"
        vpc_subnet_id: "{{public_sub_1.subnet.id }}"
        volumes:
          - device_name: /dev/sdb
            volume_type: gp3
            volume_size: 200
            delete_on_termination: false
        instance_tags:
          Name: prd-seoul-proxy-{{az_1}}
        wait: true
        count: 1
      register: ec_1
      
     - name: Create EC2 instance-2
      ec2:
        key_name: "{{key_pair}}"
        image: ami-08f90fed89a37985d
        instance_type: m5.xlarge
        region: "{{ region }}"
        vpc_subnet_id: "{{public_sub_1.subnet.id }}"
        volumes:
          - device_name: /dev/sdb
            volume_type: gp3
            volume_size: 200
            delete_on_termination: false
        instance_tags:
          Name: prd-seoul-proxy-{{az_2}}
        wait: true
        count: 1
      register: ec_2
      
    - name: Create Internet gateway
      ec2_vpc_igw:
        vpc_id: "{{vpc_1.vpc.id}}"
        region: "{{region}}"
        state: present
        tags:
          Name: prd-seoul-igw
      register: igw_1  
        
    - name: Create Route Table-Public
      ec2_vpc_route_table:
        vpc_id: "{{vpc_1.vpc.id}}"
        region: "{{region}}"
        tags:
          Name: prd-seoul-rt
        subnets:
          - "{{ public_subnet_a.subnet.id }}"
          - "{{ public_subnet_c.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{igw_1.gateway_id}}"
      register: prd_seoul_public_rt
      
     - name: Creat Loard Balancer
     
