---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Create VPC Interface 
      ec2_vpc_net:
        name: prd-seoul-vpc	
        cidr_block: "{{vpc_cidr}}"
        region: "{{region}}"
        tenancy: default
      register: vpc_1
      
    - name: Create Public-Subnet-a
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpc_1.vpc.id}}"
        cidr: "{{subnet1_cidr}}"
        region: "{{region}}"
        az: "{{az_1}}"
        tags:
          Name: prd-seoul-pulic-subnet-a
      register: prd-seoul-pulic-subnet-a
      
    - name: Create Public-Subnet-c
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpc_1.vpc.id}}"
        cidr: "{{subnet1_cidr}}"
        region: "{{region}}"
        az: "{{az_2}}"
        tags:
          Name: prd-seoul-pulic-subnet-c
      register: prd-seoul-pulic-subnet-c
          
    - name: Create Private-Subnet-2
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpc_1.vpc.id}}"
        cidr: "{{subnet2_cidr}}"
        region: "{{region}}"
        az: "{{az_2}}"
        tags:
          Name: prd-seoul-private-subnet-a
      register: prd-seoul-private-subnet-a
      
    - name: Create Bastion EC2 Instance
      ec2:
        key_name: "{{key_pair}}"
        image: ami-08f90fed89a37985d
        instance_type: t2.medium
        region: "{{ region }}"
        vpc_subnet_id: "{{ prd-seoul-public-subnet-a.subnet.id }}"
        instance_tags:
          Name: prd-seoul-bastion-a
        wait: true
        count: 1
      register: bastion_instance
      
    - name: Create NAT EC2 Instance-a
      ec2:
        key_name: "{{key_pair}}"
        image: ami-08f90fed89a37985d
        instance_type: m5.xlarge
        region: "{{ region }}"
        vpc_subnet_id: "{{ private_subnet_1.subnet.id}}"
        volumes:
          - device_name: /dev/sdb
            volume_type: gp3
            volume_size: 200
            delete_on_termination: false
        instance_tags:
          Name: prd-seoul-proxy-a
        wait: true
        count: 1
      register: prd-seoul-proxy-a
      
        - name: Create NAT EC2 Instance-c
          ec2:
            key_name: "{{key_pair}}"
            image: ami-08f90fed89a37985d
            instance_type: m5.xlarge
            region: "{{ region }}"
            vpc_subnet_id: "{{ private_subnet_2.subnet.id}}"
            volumes:
              - device_name: /dev/sdb
                volume_type: gp3
                volume_size: 200
                delete_on_termination: false
            instance_tags:
              Name: prd-seoul-proxy-c
            wait: true
            count: 1
          register: prd-seoul-proxy-c
      
    - name: Create an ELB and attach a listener
      elb_network_lb:
        subnets:
          - "{{private_subnet_1.subnet.id}}"
          - "{{private_subnet_2.subnet.id}}"
        listeners:
          - Protocol: TCP
            Port: 80 
            DefaultActions:
              - Type: forward
                TargetGroupName: mytargetgroup 
        state: present
 
    - name: Create Internet gateway
      ec2_vpc_igw:
        vpc_id: "{{vpc_1.vpc.id}}"
        region: "{{region}}"
        state: present
        tags:
          - name: prd-seoul-igw
      register: igw_1  
      
    - name: Create Nat Gateway 
      ec2_vpc_nat_gateway:
        state: present
        region: "{{region}}"
        subnet_id: "{{public_subnet_1.subnet.id}}"
      register: nat_1
        
    - name: Create Route Table-Public
      ec2_vpc_route_table:
        vpc_id: "{{vpc_1.vpc.id}}"
        region: "{{region}}"
        tags:
          Name: prd-seoul-rt
        subnets:
          - "{{ prd-seoul-pulic-subnet-a }}"
          - "{{ prd-seoul-pulic-subnet-c }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{igw_1.gateway_id}}"
      register: prd-seoul-public-rt

    - name: Create Route Table-internal
      ec2_vpc_route_table:
        vpc_id: "{{vpc_1.vpc.id}}"
        region: "{{region}}"
        tags:
          Name: Internal
        subnets:
          - "{{ private_subnet_1.subnet.id }}"
          - "{{ private_subnet_2.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
      register: prd-seoul-private-rt
