---
- name: Create VPC Interface 
  ec2_vpc_net:
    name: ansible-vpc-test	
    cidr_block: 10.0.0.0/16
    region: ap-northeast-2
    tags:
      module: ec2_vpc_net
      this: works
    tenancy: dedicated
