- name: Create VPC Interface 
      ec2_vpc_net:
        name: prd-seoul-vpc	
        cidr_block: "{{vpc_cidr}}"
        region: "{{region}}"
        tenancy: default
      register: vpc_1
      
    - name: Create Public-Subnet-a
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpc_1.vpc.id}}"
        cidr: "{{public_subnet_a_cidr}}"
        region: "{{region}}"
        az: "{{az_1}}"
        tags:
          Name: prd-seoul-pulic-subnet-a
      register: public_subnet_a
      
    - name: Create Public-Subnet-c
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpc_1.vpc.id}}"
        cidr: "{{public_subnet_c_cidr}}"
        region: "{{region}}"
        az: "{{az_2}}"
        tags:
          Name: prd-seoul-pulic-subnet-c
      register: public_subnet_c
